# Dependencies
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Colin Cross
tagline:          'Chicago Software Developer'
description:      'Software Developer at <a href="https://twitter.com/rally_health">Rally Health</a> in Chicago.'
url:              http://alarmingcow.github.io
baseurl:          /

author:
  name:           'Colin Cross'
  url:            https://twitter.com/AlarmingCow

paginate:         5

# Custom vars
