# Dependencies
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Colin Cross
tagline:          'Chicago Software Developer'
description:      'Software Developer in Chicago. Currently leading application scaling efforts at at <a href="https://twitter.com/Backstop">Backstop</a>.'
url:              http://alarmingcow.github.io
baseurl:          /

author:
  name:           'Colin Cross'
  url:            https://twitter.com/AlarmingCow

paginate:         5

# Custom vars
